// <auto-generated />
using System;
using Loja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250318001141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Loja.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descritivo")
                        .HasColumnType("longtext");

                    b.Property<int>("Fk_id_produto")
                        .HasColumnType("int");

                    b.Property<int?>("produtoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("produtoId");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("Loja.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_compra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Fk_id_item")
                        .HasColumnType("int");

                    b.Property<string>("Fk_id_usuario")
                        .HasColumnType("longtext");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("compra");
                });

            modelBuilder.Entity("Loja.Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fk_id_compra")
                        .HasColumnType("int");

                    b.Property<int>("Fk_id_produto")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("compraId")
                        .HasColumnType("int");

                    b.Property<int?>("produtoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("compraId");

                    b.HasIndex("produtoId");

                    b.ToTable("item");
                });

            modelBuilder.Entity("Loja.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Descricao_produto")
                        .HasColumnType("int");

                    b.Property<int>("Fk_id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("Nome_produto")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("Loja.Models.ProdutoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fk_id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("Fk_id_produto")
                        .HasColumnType("int");

                    b.Property<int?>("categoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("produtoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.HasIndex("produtoId");

                    b.ToTable("produto_categoria");
                });

            modelBuilder.Entity("Loja.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_usuario")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Loja.Models.Categoria", b =>
                {
                    b.HasOne("Loja.Models.Produto", "produto")
                        .WithMany("categoria")
                        .HasForeignKey("produtoId");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Loja.Models.Compra", b =>
                {
                    b.HasOne("Loja.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Loja.Models.Itens", b =>
                {
                    b.HasOne("Loja.Models.Compra", "compra")
                        .WithMany("item")
                        .HasForeignKey("compraId");

                    b.HasOne("Loja.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId");

                    b.Navigation("compra");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Loja.Models.ProdutoCategoria", b =>
                {
                    b.HasOne("Loja.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId");

                    b.HasOne("Loja.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId");

                    b.Navigation("categoria");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Loja.Models.Compra", b =>
                {
                    b.Navigation("item");
                });

            modelBuilder.Entity("Loja.Models.Produto", b =>
                {
                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
